//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Models.Resources.StringResource", typeof(StringResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treść wiadomości jest wymagana..
        /// </summary>
        internal static string BodyRequired {
            get {
                return ResourceManager.GetString("BodyRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maksymalna długość dla pola Miasto to 40 znaków..
        /// </summary>
        internal static string CityMaxLength {
            get {
                return ResourceManager.GetString("CityMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miasto jest wymagane..
        /// </summary>
        internal static string CityRequired {
            get {
                return ResourceManager.GetString("CityRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wartosc powinna byc wieksza anizeli OD.
        /// </summary>
        internal static string Clat_To_Wartosc_powinna_byc_wieksza_anizeli_OD {
            get {
                return ResourceManager.GetString("Clat_To_Wartosc_powinna_byc_wieksza_anizeli_OD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opis jest wymagany..
        /// </summary>
        internal static string DescriptionRequired {
            get {
                return ResourceManager.GetString("DescriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maksymalna długość dla pola Email to 40 znaków..
        /// </summary>
        internal static string EmailMaxLength {
            get {
                return ResourceManager.GetString("EmailMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres email nie jest prawidłowy..
        /// </summary>
        internal static string EmailNotValid {
            get {
                return ResourceManager.GetString("EmailNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres email jest wymagany..
        /// </summary>
        internal static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maksymalna długość dla pola Imię to 20 znaków..
        /// </summary>
        internal static string FirstNameMaxLength {
            get {
                return ResourceManager.GetString("FirstNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imię jest wymagane..
        /// </summary>
        internal static string FirstNameRequired {
            get {
                return ResourceManager.GetString("FirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maksymalna długość dla pola Imię i Nazwisko to 40 znaków..
        /// </summary>
        internal static string FullNameMaxLength {
            get {
                return ResourceManager.GetString("FullNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imię i nazwisko są wymagane..
        /// </summary>
        internal static string FullNameRequired {
            get {
                return ResourceManager.GetString("FullNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maksymalna długość dla pola Nazwisko to 20 znaków..
        /// </summary>
        internal static string LastNameMaxLength {
            get {
                return ResourceManager.GetString("LastNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwisko jest wymagane..
        /// </summary>
        internal static string LastNameRequired {
            get {
                return ResourceManager.GetString("LastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numer telefonu jest wymagany..
        /// </summary>
        internal static string PhoneFirstRequired {
            get {
                return ResourceManager.GetString("PhoneFirstRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numer telefonu nie jest poprawny. Poprawny numer składa się z 6-18 cyfr.
        /// </summary>
        internal static string PhoneNotValid {
            get {
                return ResourceManager.GetString("PhoneNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numer telefonu jest wymagany..
        /// </summary>
        internal static string PhoneNumberRequired {
            get {
                return ResourceManager.GetString("PhoneNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prawidłowy format ceny to: 12, 12.32, Do negocjacji.
        /// </summary>
        internal static string PriceAdvertNotValid {
            get {
                return ResourceManager.GetString("PriceAdvertNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cena powinna składać się z maksymalnie 7 cyfr..
        /// </summary>
        internal static string PriceNotValid {
            get {
                return ResourceManager.GetString("PriceNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cena jest wymagana..
        /// </summary>
        internal static string PriceRequired {
            get {
                return ResourceManager.GetString("PriceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ilość pokoi musi być pomiędzy {1}, a {2}..
        /// </summary>
        internal static string RoomsRange {
            get {
                return ResourceManager.GetString("RoomsRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ilość kondygnacji musi być pomiędzy {1}, a {2}..
        /// </summary>
        internal static string StoreyRange {
            get {
                return ResourceManager.GetString("StoreyRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maksymalna długość tytułu to 40 znaków..
        /// </summary>
        internal static string TitleMaxLength {
            get {
                return ResourceManager.GetString("TitleMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tytuł jest wymagany..
        /// </summary>
        internal static string TitleRequired {
            get {
                return ResourceManager.GetString("TitleRequired", resourceCulture);
            }
        }
    }
}
